apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: evebox
  name: evebox
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evebox
  template:
    metadata:
      annotations:
      labels:
        app: evebox
    spec:
      automountServiceAccountToken: false

      containers:
        - args:
            - -e
            - http://elasticsearch.logging:9200
          image: jasonish/evebox
          name: evebox

          ports:
            - name: web
              containerPort: 5636

          resources:
            requests:
              memory: 50Mi
              cpu: 50m
            limits:
              cpu: 100m
              memory: 100Mi

          livenessProbe:
            httpGet:
              path: /
              port: web
          readinessProbe:
            httpGet:
              path: /
              port: web
          # Need to wait for Elasticsearch
          startupProbe:
            failureThreshold: 6
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            httpGet:
              path: /
              port: web

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 10000
            runAsNonRoot: true
            runAsUser: 10000
            seccompProfile:
              type: RuntimeDefault

      restartPolicy: Always
